Analysis of a Books dataset found at https://www.kaggle.com/datasets/thedevastator/books-sales-and-ratings

In [123]:
import numpy as np
import pandas as pd

books = pd.read_csv('/kaggle/input/datasets/thedevastator/books-sales-and-ratings/Books_Data_Clean.csv')

print('Done.')

Done.

In [124]:
#What kind of information this dataset contains?
books.columns

Index(['index', 'Publishing Year', 'Book Name', 'Author', 'language_code',
       'Author_Rating', 'Book_average_rating', 'Book_ratings_count', 'genre',
       'gross sales', 'publisher revenue', 'sale price', 'sales rank',
       'Publisher ', 'units sold'],
      dtype='object')

In [125]:
#Checking data types and if there are any missing values
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1070 non-null   int64
 1   Publishing Year      1069 non-null   float64
 2   Book Name            1047 non-null   object
 3   Author               1070 non-null   object
 4   language_code        1017 non-null   object
 5   Author_Rating        1070 non-null   object
 6   Book_average_rating  1070 non-null   float64
 7   Book_ratings_count   1070 non-null   int64
 8   genre                1070 non-null   object
 9   gross sales          1070 non-null   float64
 10  publisher revenue    1070 non-null   float64
 11  sale price           1070 non-null   float64
 12  sales rank           1070 non-null   int64
 13  Publisher            1070 non-null   object
 14  units sold           1070 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 125.5+ KB

In [126]:
#Checking missing value for 'Publishing Year'
books[books['Publishing Year'].isna()]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
445,445,NaN,NaN,"Robert Kapilow, Dr. Seuss",NaN,Famous,4.44,90574,nonfiction,532.22,319.332,2.99,493,Hachette Book Group,4806

In [127]:
#Removing missing value for 'Publishing Year' as 'Book Name' is also missing
books_v2 = books.dropna(subset = 'Publishing Year', how = 'all')

In [128]:
#Checking & removing missing values for 'Book Name'
books_v2[books_v2['Book Name'].isna()]
books_v3 = books_v2.dropna(subset = 'Book Name', how = 'all')

In [129]:
#Checking values for language_code
books_v3['language_code'].value_counts()

language_code
eng      725
en-US    228
en-GB     29
en-CA      7
fre        4
spa        2
ara        2
nl         1
Name: count, dtype: int64

In [130]:
#Renaming 'language_code' values for readability
books_v3['language_code'] = books_v3['language_code'].replace({
    'eng': 'english',
    'en-US': 'english',
    'en-GB': 'english',
    'en-CA': 'english',
    'fre': 'french',
    'spa': 'spanish',
    'ara': 'arabic',
    'nl': 'dutch'
})

books_v3['language_code'].value_counts()

/tmp/ipykernel_58/1545667673.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_v3['language_code'] = books_v3['language_code'].replace({

language_code
english    989
french       4
spanish      2
arabic       2
dutch        1
Name: count, dtype: int64

In [131]:
#Checking missing values for language_code
books_v3[books_v3['language_code'].isna()]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
22,22,1991.0,Needful Things,Stephen King,NaN,Intermediate,3.87,153821,genre fiction,2772.00,0.000,0.99,23,"Amazon Digital Services, Inc.",2800
74,74,2007.0,"Are You There, Vodka? It's Me, Chelsea",Chelsea Handler,NaN,Intermediate,3.85,127096,genre fiction,5462.31,3277.386,3.99,76,Hachette Book Group,1369
109,109,2002.0,Prey,Michael Crichton,NaN,Intermediate,3.72,131352,genre fiction,1850.70,0.000,1.99,114,"Amazon Digital Services, Inc.",930
207,207,1971.0,Mrs. Frisby and the Rats of NIMH,Robert C. O'Brien,NaN,Intermediate,4.13,135978,genre fiction,1815.45,1089.270,3.99,227,"Amazon Digital Services, Inc.",455
209,209,1953.0,The Little House Collection,"Laura Ingalls Wilder, Garth Williams",NaN,Intermediate,4.33,124320,genre fiction,5195.91,3117.546,11.47,228,Random House LLC,453
210,210,1998.0,The Girls' Guide to Hunting and Fishing,Melissa Bank,NaN,Novice,3.29,113977,nonfiction,448.47,0.000,0.99,228,"Amazon Digital Services, Inc.",453
256,256,2010.0,Sh*t My Dad Says,Justin Halpern,NaN,Intermediate,3.98,102560,nonfiction,2775.00,1665.000,7.50,278,Hachette Book Group,370
259,259,1997.0,The Four Agreements: A Practical Guide to Pers...,Miguel Ruiz,NaN,Intermediate,4.12,97016,genre fiction,4388.34,2633.004,11.99,280,Penguin Group (USA) LLC,366
267,267,1960.0,"One Fish, Two Fish, Red Fish, Blue Fish",Dr. Seuss,NaN,Intermediate,4.12,117582,nonfiction,706.45,423.870,1.99,287,Simon and Schuster Digital Sales Inc,355
268,268,1987.0,Watchers,Dean Koontz,NaN,Intermediate,4.16,109595,genre fiction,1049.49,0.000,2.99,289,"Amazon Digital Services, Inc.",351
382,382,1931.0,The Joy of Cooking,"Irma S. Rombauer, Marion Rombauer Becker, Etha...",NaN,Excellent,4.14,102348,fiction,1864.03,1118.418,8.59,415,Hachette Book Group,5859
427,427,1908.0,The Complete Anne of Green Gables Boxed Set,L.M. Montgomery,NaN,Famous,4.42,92142,genre fiction,1510.11,906.066,7.99,472,Random House LLC,5103
432,432,1997.0,The Partner,John Grisham,NaN,Intermediate,3.89,86870,genre fiction,746.13,0.000,3.99,476,"Amazon Digital Services, Inc.",5049
435,435,1986.0,Presumed Innocent,Scott Turow,NaN,Excellent,4.10,91774,genre fiction,553.15,331.890,2.99,479,"Amazon Digital Services, Inc.",4995
446,446,1320.0,Inferno,"Dante Alighieri, Anthony M. Esolen",NaN,Intermediate,3.99,87511,fiction,354.22,212.532,1.99,493,Hachette Book Group,4806
455,455,1999.0,The Girl Who Loved Tom Gordon,Stephen King,NaN,Intermediate,3.56,95768,nonfiction,1346.76,808.056,7.74,503,"Amazon Digital Services, Inc.",4698
461,461,2005.0,The Twilight Saga,"Stephenie Meyer, Ilyana Kadushin, Matt Walters",NaN,Intermediate,3.88,89204,genre fiction,1632.28,979.368,9.49,513,Penguin Group (USA) LLC,4644
481,481,2012.0,The Secret Keeper,Kate Morton,NaN,Excellent,4.13,89460,genre fiction,332.33,199.398,1.99,532,HarperCollins Publishers,4509
482,482,1953.0,Better Homes & Gardens New Cook Book,Better Homes and Gardens,NaN,Excellent,4.14,93640,nonfiction,165.33,0.000,0.99,534,"Amazon Digital Services, Inc.",4509
523,523,2012.0,Reached,Ally Condie,NaN,Intermediate,3.56,109290,genre fiction,155.43,0.000,0.99,580,"Amazon Digital Services, Inc.",4239
526,526,1999.0,The Testament,John Grisham,NaN,Intermediate,3.83,80377,nonfiction,778.44,467.064,4.99,585,Random House LLC,4212
566,566,2004.0,90 Minutes in Heaven,"Don Piper, Cecil Murphey",NaN,Intermediate,3.91,67937,genre fiction,1251.22,750.732,8.57,631,"Amazon Digital Services, Inc.",3942
572,572,2001.0,Sam's Letters To Jennifer,James Patterson,NaN,Excellent,4.15,77538,genre fiction,868.55,521.130,5.99,636,Hachette Book Group,3915
576,576,2004.0,Little Earthquakes,Jennifer Weiner,NaN,Intermediate,3.76,77592,nonfiction,1072.50,643.500,7.50,645,Random House LLC,3861
593,593,2002.0,Lullaby,Chuck Palahniuk,NaN,Intermediate,3.73,66713,genre fiction,1094.63,656.778,7.99,671,Hachette Book Group,53352
602,602,1992.0,The English Patient,Michael Ondaatje,NaN,Intermediate,3.88,83741,genre fiction,663.67,0.000,4.99,688,"Amazon Digital Services, Inc.",51840
646,646,2010.0,Warm Bodies,Isaac Marion,NaN,Intermediate,3.93,66381,genre fiction,486.78,292.068,3.99,740,"Amazon Digital Services, Inc.",43848
654,654,1984.0,Cold Sassy Tree,Olive Ann Burns,NaN,Intermediate,3.99,82281,genre fiction,950.81,570.486,7.99,751,Random House LLC,42120
672,672,2012.0,Aristotle and Dante Discover the Secrets of th...,Benjamin Alire SÃ¡enz,NaN,Excellent,4.34,108884,fiction,1082.90,649.740,9.10,770,"Amazon Digital Services, Inc.",38232
690,690,1998.0,Summer Sisters,Judy Blume,NaN,Intermediate,3.83,73515,genre fiction,862.58,517.548,7.31,794,Penguin Group (USA) LLC,36504
709,709,1891.0,A Scandal in Bohemia,"Ronald Holt, Arthur Conan Doyle",NaN,Excellent,4.22,65422,nonfiction,352.82,211.692,2.99,814,"Amazon Digital Services, Inc.",35208
714,714,2000.0,The Brethren,John Grisham,NaN,Intermediate,3.71,69351,fiction,942.82,565.692,7.99,820,Penguin Group (USA) LLC,34992
746,746,1988.0,The Case for Christ,Lee Strobel,NaN,Excellent,4.10,67128,genre fiction,799.11,479.466,6.83,859,Macmillan,31752
789,789,1914.0,Sherlock Holmes: The Complete Novels and Stori...,"Arthur Conan Doyle, Kyle Freeman",NaN,Famous,4.46,66857,nonfiction,1263.85,758.310,10.99,914,Random House LLC,2916
846,846,2002.0,Janet Evanovich Three and Four Two-Book Set (S...,Janet Evanovich,NaN,Excellent,4.34,63691,genre fiction,169.50,101.700,1.50,992,HarperCollins Publishers,2889
887,887,1983.0,Magician's Gambit,David Eddings,NaN,Excellent,4.13,69616,genre fiction,334.88,0.000,2.99,1042,"Amazon Digital Services, Inc.",4440
895,895,1999.0,Keeping Faith,Jodi Picoult,NaN,Intermediate,3.79,62405,genre fiction,109.89,0.000,0.99,1052,"Amazon Digital Services, Inc.",4400
913,913,1982.0,Ham on Rye,Charles Bukowski,NaN,Excellent,4.16,54140,genre fiction,196.47,0.000,1.77,1071,"Amazon Digital Services, Inc.",4360
915,915,2003.0,Emotional Intelligence 2.0,"Travis Bradberry, Jean Greaves, Patrick Lencioni",NaN,Intermediate,3.81,53384,genre fiction,109.89,0.000,0.99,1073,"Amazon Digital Services, Inc.",4360
916,916,1941.0,Make Way for Ducklings,Robert McCloskey,NaN,Excellent,4.21,70704,nonfiction,637.14,382.284,5.74,1074,HarperCollins Publishers,4360
964,964,2005.0,PostSecret: Extraordinary Confessions from Ord...,Frank Warren,NaN,Excellent,4.01,58841,nonfiction,107.91,0.000,0.99,1138,"Amazon Digital Services, Inc.",4280
966,966,1952.0,The Borrowers Afield,"Mary Norton, Beth Krush, Joe Krush",NaN,Excellent,4.02,74820,genre fiction,706.32,423.792,6.48,1141,Hachette Book Group,4240
1012,1012,2012.0,The Racketeer,John Grisham,NaN,Intermediate,3.79,48286,genre fiction,322.92,193.752,2.99,1198,"Amazon Digital Services, Inc.",108
1025,1025,2012.0,Opal,Jennifer L. Armentrout,NaN,Excellent,4.34,92014,genre fiction,105.93,0.000,0.99,1213,"Amazon Digital Services, Inc.",107
1026,1026,2008.0,Zeitoun,Dave Eggers,NaN,Excellent,4.08,55398,genre fiction,408.74,0.000,3.82,1214,"Amazon Digital Services, Inc.",107
1032,1032,2012.0,Pines,Blake Crouch,NaN,Intermediate,3.88,34789,genre fiction,105.93,0.000,0.99,1218,"Amazon Digital Services, Inc.",107
1033,1033,1994.0,Disclosure,Michael Crichton,NaN,Intermediate,3.76,57818,genre fiction,854.93,512.958,7.99,1219,Random House LLC,107
1059,1059,1955.0,Beezus and Ramona,Beverly Cleary,NaN,Intermediate,3.97,75987,genre fiction,740.94,444.564,6.99,1257,Random House LLC,106
1060,1060,1972.0,The Farthest Shore,Ursula K. Le Guin,NaN,Excellent,4.11,65626,nonfiction,210.94,0.000,1.99,1258,"Amazon Digital Services, Inc.",106

In [132]:
#Assuming all books with NA value for 'language_code' are written in english based on their title
books_v3['language_code'] = books_v3['language_code'].fillna('english')
books_v3[books_v3['language_code'].isna()]

/tmp/ipykernel_58/45900483.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books_v3['language_code'] = books_v3['language_code'].fillna('english')

Empty DataFrame
Columns: [index, Publishing Year, Book Name, Author, language_code, Author_Rating, Book_average_rating, Book_ratings_count, genre, gross sales, publisher revenue, sale price, sales rank, Publisher , units sold]
Index: []

In [133]:
#Checking the publication window
books_v3['Publishing Year'].agg(['min', 'max'])

min    -560.0
max    2016.0
Name: Publishing Year, dtype: float64

In [134]:
#Checking if books published before year 0 are inaccuracies or valid entries
books_v3[books_v3['Publishing Year'] < 0]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
241,241,-380.0,Î Î¿Î»Î¹Ï„ÎµÎ¯Î±,"Plato, Desmond Lee",english,Intermediate,3.90,110274,genre fiction,387.09,232.254,0.99,265,"Amazon Digital Services, Inc.",391
293,293,-430.0,ÎŸá¼°Î´Î¯Ï€Î¿Ï…Ï‚ Î¤ÏÏÎ±Î½Î½Î¿Ï‚,"Sophocles, J.E. Thomas",english,Intermediate,3.67,119496,genre fiction,2460.92,1476.552,7.99,315,Hachette Book Group,308
568,568,-300.0,é“å¾·ç¶“ [dÃ o dÃ© jÄ«ng],"Lao Tzu, Gia-Fu Feng, Jane English, Chungliang...",english,Excellent,4.31,39863,genre fiction,665.55,399.330,4.59,632,Penguin Group (USA) LLC,3915
589,589,-560.0,Aesopica,"Aesop, Laura Harris, Laura Gibbs",english,Excellent,4.05,88508,genre fiction,693.61,0.000,4.99,663,"Amazon Digital Services, Inc.",53784
749,749,-17.0,Ã†neis,"Virgil, Robert Fitzgerald",english,Intermediate,3.81,75051,genre fiction,114.84,0.000,0.99,863,"Amazon Digital Services, Inc.",31752
990,990,-441.0,á¼ˆÎ½Ï„Î¹Î³ÏŒÎ½Î·,"Sophocles, J.E. Thomas",english,Intermediate,3.60,67608,genre fiction,106.92,64.152,0.99,1167,"Amazon Digital Services, Inc.",108

In [135]:
#Let's focus on modern books by removing the ones published before 1800s
books_v4 = books_v3[books_v3['Publishing Year'] >= 1800]
books_v4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1029 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1029 non-null   int64
 1   Publishing Year      1029 non-null   float64
 2   Book Name            1029 non-null   object
 3   Author               1029 non-null   object
 4   language_code        1029 non-null   object
 5   Author_Rating        1029 non-null   object
 6   Book_average_rating  1029 non-null   float64
 7   Book_ratings_count   1029 non-null   int64
 8   genre                1029 non-null   object
 9   gross sales          1029 non-null   float64
 10  publisher revenue    1029 non-null   float64
 11  sale price           1029 non-null   float64
 12  sales rank           1029 non-null   int64
 13  Publisher            1029 non-null   object
 14  units sold           1029 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 128.6+ KB

In [136]:
#Checking if there are any duplicate records in 'Book Name' column
books_v4['Book Name'].value_counts()

Book Name
Persepolis                                      2
The Awakening                                   2
Cosmos                                          1
Haunted: A Novel of Stories                     1
The Shell Seekers                               1
                                               ..
Fool Moon                                       1
Lover Eternal (Black Dagger Brotherhood, #2)    1
Harold and the Purple Crayon                    1
As I Lay Dying                                  1
We Need to Talk About Kevin                     1
Name: count, Length: 1027, dtype: int64

In [137]:
#Checking books that are present in duplicates
books_v4[books_v4['Book Name'] == 'Persepolis'] 
#Multiple tomes of that book so valid entries

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
297,297,2000.0,Persepolis,"Marjane Satrapi, Mattias Ripa",english,Excellent,4.23,117103,genre fiction,1487.02,892.212,4.99,321,Random House LLC,298
933,933,2003.0,Persepolis,"Marjane Satrapi, Mattias Ripa, Blake Ferris, A...",english,Excellent,4.36,71353,nonfiction,108.90,0.000,0.99,1099,"Amazon Digital Services, Inc.",4320

In [138]:
#Checking books that are present in duplicates
books_v4[books_v4['Book Name'] == 'The Awakening']
#Different writers so valid entries

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
251,251,1899.0,The Awakening,Kate Chopin,english,Intermediate,3.63,125474,genre fiction,371.25,0.00,0.99,275,"Amazon Digital Services, Inc.",375
696,696,2009.0,The Awakening,Kelley Armstrong,english,Excellent,4.16,95026,genre fiction,761.10,456.66,6.45,802,Simon and Schuster Digital Sales Inc,36072

In [139]:
#Checking if there are any unreadable 'Book Name'
mask = books_v4['Book Name'].str.match(
    r'^(ã|æ|è|ä|é|å|ç)',
    na=False
)

print(books_v4.loc[mask, 'Book Name'])

54     ãƒ‡ã‚¹ãƒŽãƒ¼ãƒˆ #1 (Desu NÅto) Taikutsu (é€€å±ˆ)
118    ã„ã¡ãã‚…ã†ã¯ã¡ã‚ˆã‚“ [Ichi-KyÅ«-Hachi-Yon]
272                        ãƒ•ãƒ«ãƒ¼ãƒ„ãƒã‚¹ã‚±ãƒƒãƒˆ 1
279                           æ¡œè˜­é«˜æ ¡ãƒ›ã‚¹ãƒˆéƒ¨ 1
362                                 é‹¼ã®éŒ¬é‡‘è¡“å¸« 1
389              äººç”ŸãŒã¨ãã‚ãç‰‡ã¥ã‘ã®é­”æ³•
551    è‰²å½©ã‚’æŒãŸãªã„å¤šå´Žã¤ãã‚‹ã¨ã€å½¼ã...
595                           ãƒ´ã‚¡ãƒ³ãƒ‘ã‚¤ã‚¢é¨Žå£« 1
652                                    é€²æ’ƒã®å·¨äºº 1
674    ä¸–ç•Œã®çµ‚ã‚Šã¨ãƒãƒ¼ãƒ‰ãƒœã‚¤ãƒ«ãƒ‰ãƒ»ãƒ¯ã...
739    ã‚¹ãƒ—ãƒ¼ãƒˆãƒ‹ã‚¯ã®æ‹äºº [SupÅ«toniku no Ko...
751                 ã‚¢ãƒ•ã‚¿ãƒ¼ãƒ€ãƒ¼ã‚¯ [AfutÄ dÄku]
821                         é»’åŸ·äº‹ I [Kuroshitsuji I]
969        ç¾Šã‚’ã‚ãã‚‹å†’é™º [HitsujiwomegurubÅken]
Name: Book Name, dtype: object

In [140]:
#Removing rows for unreadable 'Book Name'
books_v4 = books_v4[~mask]
print(books_v4.loc[mask, 'Book Name'])

Series([], Name: Book Name, dtype: object)

In [141]:
#Checking that 'Book Name' doesn't contain any other unreadable titles by looking at 
#titles that start with at least 5 non-Latin characters
mask2 = books_v4['Book Name'].str.match(
    r'^[^A-Za-zÀ-ÿ]{5,}',
    na=False
)

print(books_v4.loc[mask2, 'Book Name'])

Series([], Name: Book Name, dtype: object)

In [142]:
#Checking consistency in 'genre' column
books_v4['genre'].value_counts()

genre
genre fiction    780
nonfiction       163
fiction           57
children          15
Name: count, dtype: int64

In [143]:
#Renaming 'genre' values for readability
books_v4['genre'] = books_v4['genre'].replace({
    'genre fiction' : 'fiction'
})

books_v4['genre'].value_counts()

genre
fiction       837
nonfiction    163
children       15
Name: count, dtype: int64

In [144]:
#Checking that there are no missing values anymore
books_v4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1015 entries, 0 to 1069
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1015 non-null   int64
 1   Publishing Year      1015 non-null   float64
 2   Book Name            1015 non-null   object
 3   Author               1015 non-null   object
 4   language_code        1015 non-null   object
 5   Author_Rating        1015 non-null   object
 6   Book_average_rating  1015 non-null   float64
 7   Book_ratings_count   1015 non-null   int64
 8   genre                1015 non-null   object
 9   gross sales          1015 non-null   float64
 10  publisher revenue    1015 non-null   float64
 11  sale price           1015 non-null   float64
 12  sales rank           1015 non-null   int64
 13  Publisher            1015 non-null   object
 14  units sold           1015 non-null   int64
dtypes: float64(5), int64(4), object(6)
memory usage: 126.9+ KB

In [145]:
#Droping 'gross sales' & 'sales rank' columns
books_v5 = books_v4.drop(columns = ['gross sales', 'sales rank'])
books_v5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1015 entries, 0 to 1069
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                1015 non-null   int64
 1   Publishing Year      1015 non-null   float64
 2   Book Name            1015 non-null   object
 3   Author               1015 non-null   object
 4   language_code        1015 non-null   object
 5   Author_Rating        1015 non-null   object
 6   Book_average_rating  1015 non-null   float64
 7   Book_ratings_count   1015 non-null   int64
 8   genre                1015 non-null   object
 9   publisher revenue    1015 non-null   float64
 10  sale price           1015 non-null   float64
 11  Publisher            1015 non-null   object
 12  units sold           1015 non-null   int64
dtypes: float64(4), int64(3), object(6)
memory usage: 111.0+ KB

In [146]:
#Creating a new 'Gross sales' column for accuracy
books_v5['Gross sales'] = books_v5['units sold'] * books_v5['sale price']
books_v5.head(10)

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",english,Novice,3.42,155903,fiction,20496.000,4.88,HarperCollins Publishers,7000,34160.00
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",english,Intermediate,4.23,145267,fiction,7462.500,1.99,HarperCollins Publishers,6250,12437.50
2,2,2015.0,Go Set a Watchman,Harper Lee,english,Novice,3.31,138669,fiction,28677.000,8.69,"Amazon Digital Services, Inc.",5500,47795.00
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,english,Intermediate,4.04,150898,fiction,24750.000,7.50,Hachette Book Group,5500,41250.00
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,english,Intermediate,4.04,198283,fiction,22771.500,7.99,Penguin Group (USA) LLC,4750,37952.50
5,5,2015.0,Red Queen,Victoria Aveyard,english,Intermediate,4.08,83354,fiction,0.000,4.99,"Amazon Digital Services, Inc.",4000,19960.00
6,6,2011.0,The Power of Habit,Charles Duhigg,english,Intermediate,4.03,155977,fiction,16495.002,6.99,HarperCollins Publishers,3933,27491.67
7,7,1994.0,Midnight in the Garden of Good and Evil,John Berendt,english,Intermediate,3.90,167997,nonfiction,15709.200,6.89,Hachette Book Group,3800,26182.00
8,8,2012.0,Hopeless,Colleen Hoover,english,Intermediate,4.34,189938,fiction,15656.202,6.99,HarperCollins Publishers,3733,26093.67
9,9,1905.0,A Little Princess,"Frances Hodgson Burnett, Nancy Bond",english,Intermediate,4.20,199872,fiction,14275.404,6.49,Random House LLC,3666,23792.34

In [147]:
#Analysis
#What is the publication period?
books_v5['Publishing Year'].agg(['min', 'max'])

min    1812.0
max    2016.0
Name: Publishing Year, dtype: float64

In [148]:
#Analysis
#Which is the most represented language?
books_v5['language_code'].value_counts()

language_code
english    1006
french        4
spanish       2
arabic        2
dutch         1
Name: count, dtype: int64

In [149]:
#Analysis
#What is the most profitable genre?
books_v5.groupby('genre')['Gross sales'].sum()

genre
children       1695758.32
fiction       38780563.26
nonfiction     8113654.40
Name: Gross sales, dtype: float64

In [150]:
#Analysis
#Is the most profitable genre the one with the most units sold?
books_v5.groupby('genre')['units sold'].sum()

genre
children       298118
fiction       8022741
nonfiction    1562609
Name: units sold, dtype: int64

In [151]:
#Analysis
#What is the average price for each genre?
books_v5.groupby('genre')['sale price'].mean()

genre
children      6.126667
fiction       4.738244
nonfiction    5.382331
Name: sale price, dtype: float64

In [152]:
#Analysis
#What is the average rating for each genre?
books_v5.groupby('genre')['Book_average_rating'].mean()

genre
children      4.033333
fiction       4.001231
nonfiction    4.015337
Name: Book_average_rating, dtype: float64

In [153]:
#Analysis
#Which book was the best-seller?
best_seller = books_v5.loc[
    books_v5['units sold'].idxmax(),
    ['genre', 'Book Name', 'Author', 'Publishing Year', 'units sold']
]
print(best_seller)

genre                                                        fiction
Book Name          New Moon: The Complete Illustrated Movie Compa...
Author                                                Mark Cotta Vaz
Publishing Year                                               2009.0
units sold                                                     61560
Name: 578, dtype: object

In [154]:
#Analysis
#Which book was the most sold for each genre?
top_books = books_v5.loc[
    books_v5.groupby('genre')['units sold'].idxmax(),
    ['genre', 'Book Name', 'Author', 'Publishing Year', 'Book_average_rating', 'units sold']
]

print(top_books)

          genre                                          Book Name  \
611    children                                      Cryptonomicon
578     fiction  New Moon: The Complete Illustrated Movie Compa...
588  nonfiction                                  A Crown of Swords

              Author  Publishing Year  Book_average_rating  units sold
611  Neal Stephenson           1999.0                 4.25       50112
578   Mark Cotta Vaz           2009.0                 4.34       61560
588    Robert Jordan           1996.0                 4.00       54000

In [155]:
#Analysis
#Are the most sold books written by highly rated authors?
books_v5.groupby('Author_Rating')['units sold'].sum()

Author_Rating
Excellent       4560953
Famous           286759
Intermediate    4823960
Novice           211796
Name: units sold, dtype: int64

In [156]:
#Analysis
#What are the highest-rated books in each genre?
highest_ratings = books_v5.loc[
    books_v5.groupby('genre')['Book_average_rating'].idxmax(),
    ['genre', 'Book Name', 'Author', 'Publishing Year', 'Book_average_rating']
]
print(highest_ratings)

          genre                  Book Name                        Author  \
952    children  Lover Enshrined, part two                     J.R. Ward
331     fiction          Words of Radiance             Brandon Sanderson
249  nonfiction          Calvin and Hobbes  Bill Watterson, G.B. Trudeau

     Publishing Year  Book_average_rating
952           2009.0                 4.38
331           2014.0                 4.77
249           1987.0                 4.61

In [157]:
#Analysis
#In which years were the most books published?
high_publication_years = books_v5['Publishing Year'].sort_values(ascending = True).value_counts()
high_publication_years.head()

Publishing Year
2012.0    65
2011.0    53
2009.0    44
2010.0    42
2006.0    40
Name: count, dtype: int64

In [158]:
#Analysis
#Which authors have the largest publication windows?
publication_min = books_v5.groupby('Author')['Publishing Year'].min()
publication_max = books_v5.groupby('Author')['Publishing Year'].max()
publication_window = publication_max - publication_min
publication_window.sort_values(ascending = False).head(10)

Author
Stephen King                            36.0
Ken Follett                             34.0
Judy Blume                              28.0
Michael Crichton                        24.0
Barbara Kingsolver                      24.0
Laura Ingalls Wilder, Garth Williams    21.0
John Grisham                            20.0
Arthur C. Clarke                        20.0
Cormac McCarthy                         20.0
Jeffrey Eugenides                       18.0
Name: Publishing Year, dtype: float64

In [159]:
#Analysis
#Which authors have published the most books?
high_publication_rates = books_v5['Author'].value_counts()
high_publication_rates.head()

Author
Stephen King       29
John Grisham       13
Nicholas Sparks    10
Jim Butcher        10
Jodi Picoult       10
Name: count, dtype: int64

In [160]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
stephen_king_books = books_v5[books_v5['Author'] == 'Stephen King']
stephen_king_books

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
22,22,1991.0,Needful Things,Stephen King,english,Intermediate,3.87,153821,fiction,0.000,0.99,"Amazon Digital Services, Inc.",2800,2772.00
25,25,1981.0,Cujo,Stephen King,spanish,Intermediate,3.65,158215,fiction,0.000,2.99,"Amazon Digital Services, Inc.",2600,7774.00
78,78,2006.0,Cell,Stephen King,english,Intermediate,3.64,144591,fiction,3560.268,4.54,HarperCollins Publishers,1307,5933.78
81,81,1987.0,The Drawing of the Three,Stephen King,english,Intermediate,4.23,139052,nonfiction,1523.544,1.99,HarperCollins Publishers,1276,2539.24
92,92,2014.0,Mr. Mercedes,Stephen King,english,Intermediate,3.92,125847,fiction,1321.758,1.99,Macmillan,1107,2202.93
139,139,1979.0,The Dead Zone,Stephen King,english,Intermediate,3.90,132723,fiction,907.440,1.99,HarperCollins Publishers,760,1512.40
144,144,1980.0,Firestarter,Stephen King,english,Intermediate,3.85,142213,fiction,1771.560,3.99,Macmillan,740,2952.60
160,160,1999.0,On Writing: A Memoir of the Craft,Stephen King,english,Intermediate,4.31,131481,fiction,0.000,2.99,"Amazon Digital Services, Inc.",650,1943.50
172,172,1998.0,Bag of Bones,Stephen King,english,Intermediate,3.87,131004,fiction,0.000,0.99,"Amazon Digital Services, Inc.",575,569.25
208,208,1982.0,Different Seasons,Stephen King,english,Intermediate,4.34,105961,fiction,3000.270,10.99,Simon and Schuster Digital Sales Inc,455,5000.45
263,263,2013.0,Doctor Sleep,Stephen King,english,Intermediate,4.10,95276,fiction,214.434,0.99,"Amazon Digital Services, Inc.",361,357.39
380,380,1992.0,Gerald's Game,Stephen King,english,Famous,3.47,100158,fiction,260.292,1.99,"Amazon Digital Services, Inc.",5886,11713.14
413,413,1996.0,Desperation,Stephen King,english,Intermediate,3.80,94821,fiction,117.612,0.99,"Amazon Digital Services, Inc.",5346,5292.54
422,422,2004.0,The Dark Tower,Stephen King,english,Excellent,4.27,93296,fiction,0.000,3.99,"Amazon Digital Services, Inc.",5211,20791.89
436,436,1989.0,The Dark Half,Stephen King,english,Intermediate,3.74,94624,fiction,330.096,2.99,Macmillan,4968,14854.32
455,455,1999.0,The Girl Who Loved Tom Gordon,Stephen King,english,Intermediate,3.56,95768,nonfiction,808.056,7.74,"Amazon Digital Services, Inc.",4698,36362.52
592,592,1985.0,Skeleton Crew,Stephen King,english,Intermediate,3.93,82320,fiction,574.632,6.94,Random House LLC,53568,371761.92
608,608,1987.0,The Tommyknockers,Stephen King,english,Famous,3.48,89262,fiction,0.000,5.99,"Amazon Digital Services, Inc.",50760,304052.40
651,651,2013.0,Joyland,Stephen King,english,Intermediate,3.90,75018,fiction,0.000,0.99,"Amazon Digital Services, Inc.",42768,42340.32
677,677,1990.0,Four Past Midnight,Stephen King,english,Intermediate,3.90,76376,nonfiction,384.132,5.38,HarperCollins Publishers,37368,201039.84
730,730,1987.0,Eyes of the Dragon,Stephen King,english,Intermediate,3.92,72714,nonfiction,420.498,5.99,HarperCollins Publishers,33264,199251.36
808,808,1980.0,The Mist,Stephen King,english,Intermediate,3.92,82062,nonfiction,204.516,2.99,"Amazon Digital Services, Inc.",2916,8718.84
816,816,2014.0,Revival,Stephen King,english,Intermediate,3.75,53662,fiction,0.000,4.99,"Amazon Digital Services, Inc.",2916,14550.84
829,829,2008.0,Duma Key,Stephen King,english,Intermediate,3.93,73807,fiction,506.844,7.41,Macmillan,2889,21407.49
892,892,1995.0,Rose Madder,Stephen King,english,Intermediate,3.66,70921,fiction,133.728,1.99,Simon and Schuster Digital Sales Inc,4400,8756.00
959,959,2015.0,Finders Keepers,Stephen King,english,Excellent,4.03,36541,fiction,0.000,0.99,"Amazon Digital Services, Inc.",4280,4237.20
967,967,1999.0,Hearts in Atlantis,Stephen King,english,Intermediate,3.80,65063,fiction,130.146,1.99,Macmillan,4240,8437.60
1045,1045,2010.0,"Full Dark, No Stars",Stephen King,english,Excellent,4.03,60672,fiction,384.558,5.99,Random House LLC,107,640.93
1058,1058,2002.0,Everything's Eventual: 14 Dark Tales,Stephen King,english,Intermediate,3.94,60932,fiction,190.164,2.99,"Amazon Digital Services, Inc.",106,316.94

In [161]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
stephen_king_books['Author_Rating'].value_counts()

Author_Rating
Intermediate    24
Excellent        3
Famous           2
Name: count, dtype: int64

In [162]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Publication window
stephen_king_books.groupby('Author')['Publishing Year'].agg(['min', 'max'])

                 min     max
Author
Stephen King  1979.0  2015.0

In [163]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Publishing window & number of yearly publications
stephen_king_books['Publishing Year'].sort_values(ascending = False).value_counts().head(10)

Publishing Year
1987.0    3
1999.0    3
2014.0    2
1980.0    2
2013.0    2
2015.0    1
2006.0    1
2008.0    1
2010.0    1
2004.0    1
Name: count, dtype: int64

In [164]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#What is the most written genre for this author?
stephen_king_books['genre'].value_counts()

genre
fiction       24
nonfiction     5
Name: count, dtype: int64

In [165]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Which books did they sell the most?
stephen_king_books['units sold'].sort_values(ascending = False).head(3)

592    53568
608    50760
651    42768
Name: units sold, dtype: int64

In [166]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Which books did they sell the most?
stephen_king_books.loc[[592, 608, 651]]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
592,592,1985.0,Skeleton Crew,Stephen King,english,Intermediate,3.93,82320,fiction,574.632,6.94,Random House LLC,53568,371761.92
608,608,1987.0,The Tommyknockers,Stephen King,english,Famous,3.48,89262,fiction,0.000,5.99,"Amazon Digital Services, Inc.",50760,304052.40
651,651,2013.0,Joyland,Stephen King,english,Intermediate,3.90,75018,fiction,0.000,0.99,"Amazon Digital Services, Inc.",42768,42340.32

In [167]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#How many books did they sell on average?
stephen_king_books['units sold'].mean()

np.float64(9597.310344827587)

In [168]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#What is the average rating for this author?
stephen_king_books.groupby('Author')['Book_average_rating'].agg(['mean', 'min', 'max'])

                  mean   min   max
Author
Stephen King  3.886552  3.47  4.34

In [169]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Which was their highest-rated book?
stephen_king_books.loc [
    stephen_king_books.groupby('Author')['Book_average_rating'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
208,Stephen King,1982.0,Different Seasons,4.34,fiction,10.99,455,5000.45

In [170]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Which was their lowest-rated book?
stephen_king_books.loc [
    stephen_king_books.groupby('Author')['Book_average_rating'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
380,Stephen King,1992.0,Gerald's Game,3.47,fiction,1.99,5886,11713.14

In [171]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#What is their average sale price?
stephen_king_books.groupby('Author')['sale price'].agg(['mean', 'min', 'max'])

                  mean   min    max
Author
Stephen King  3.681724  0.99  10.99

In [172]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Which was their most expensive book?
stephen_king_books.loc [
    stephen_king_books.groupby('Author')['sale price'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold
208,Stephen King,1982.0,Different Seasons,4.34,fiction,10.99,455

In [173]:
#Focus on the top 3 authors who have published the most books
#Top 1: Stephen King
#Which was their least expensive book?
stephen_king_books.loc [
    stephen_king_books.groupby('Author')['sale price'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold
22,Stephen King,1991.0,Needful Things,3.87,fiction,0.99,2800

In [174]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
john_grisham_books = books_v5[books_v5['Author'] == 'John Grisham']
john_grisham_books

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
65,65,1995.0,The Rainmaker,John Grisham,english,Intermediate,3.91,137412,fiction,0.000,7.99,"Amazon Digital Services, Inc.",1507,12040.93
302,302,1994.0,The Chamber,John Grisham,english,Intermediate,3.76,102715,fiction,0.000,0.99,"Amazon Digital Services, Inc.",295,292.05
432,432,1997.0,The Partner,John Grisham,english,Intermediate,3.89,86870,fiction,0.000,3.99,"Amazon Digital Services, Inc.",5049,20145.51
506,506,1998.0,The Street Lawyer,John Grisham,english,Intermediate,3.81,80577,fiction,192.234,1.99,Random House LLC,4347,8650.53
526,526,1999.0,The Testament,John Grisham,english,Intermediate,3.83,80377,nonfiction,467.064,4.99,Random House LLC,4212,21017.88
561,561,2013.0,Sycamore Row,John Grisham,english,Intermediate,3.98,56315,fiction,644.742,7.31,Penguin Group (USA) LLC,3969,29013.39
714,714,2000.0,The Brethren,John Grisham,english,Intermediate,3.71,69351,fiction,565.692,7.99,Penguin Group (USA) LLC,34992,279586.08
770,770,2005.0,The Broker,John Grisham,english,Intermediate,3.77,65428,fiction,68.904,0.99,"Amazon Digital Services, Inc.",29592,29296.08
857,857,2004.0,The Last Juror,John Grisham,english,Intermediate,3.85,63114,nonfiction,582.402,8.59,Penguin Group (USA) LLC,2862,24584.58
876,876,2003.0,The King of Torts,John Grisham,english,Intermediate,3.67,61835,nonfiction,402.528,5.99,HarperCollins Publishers,4480,26835.20
1012,1012,2012.0,The Racketeer,John Grisham,english,Intermediate,3.79,48286,fiction,193.752,2.99,"Amazon Digital Services, Inc.",108,322.92
1042,1042,2001.0,A Painted House,John Grisham,english,Intermediate,3.67,59974,nonfiction,0.000,0.99,"Amazon Digital Services, Inc.",107,105.93
1065,1065,2014.0,Gray Mountain,John Grisham,english,Intermediate,3.52,37379,nonfiction,62.964,0.99,"Amazon Digital Services, Inc.",106,104.94

In [175]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
john_grisham_books['Author_Rating'].value_counts()

Author_Rating
Intermediate    13
Name: count, dtype: int64

In [176]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Publishing window
john_grisham_books.groupby('Author')['Publishing Year'].agg(['min', 'max'])

                 min     max
Author
John Grisham  1994.0  2014.0

In [177]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Publishing window & number of yearly publications
john_grisham_books['Publishing Year'].sort_values(ascending = False).value_counts().head(10)

Publishing Year
2014.0    1
2013.0    1
2012.0    1
2005.0    1
2004.0    1
2003.0    1
2001.0    1
2000.0    1
1999.0    1
1998.0    1
Name: count, dtype: int64

In [178]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#What is the most written genre for this author?
john_grisham_books['genre'].value_counts()

genre
fiction       8
nonfiction    5
Name: count, dtype: int64

In [179]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Which books did they sell the most?
john_grisham_books['units sold'].sort_values(ascending = False).head(3)

714    34992
770    29592
432     5049
Name: units sold, dtype: int64

In [180]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Which books did they sell the most?
john_grisham_books.loc[[714, 770, 432]]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
714,714,2000.0,The Brethren,John Grisham,english,Intermediate,3.71,69351,fiction,565.692,7.99,Penguin Group (USA) LLC,34992,279586.08
770,770,2005.0,The Broker,John Grisham,english,Intermediate,3.77,65428,fiction,68.904,0.99,"Amazon Digital Services, Inc.",29592,29296.08
432,432,1997.0,The Partner,John Grisham,english,Intermediate,3.89,86870,fiction,0.000,3.99,"Amazon Digital Services, Inc.",5049,20145.51

In [181]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#How many books did they sell on average?
john_grisham_books['units sold'].mean()

np.float64(7048.153846153846)

In [182]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#What is the average rating for this author?
john_grisham_books.groupby('Author')['Book_average_rating'].agg(['mean', 'min', 'max'])

                  mean   min   max
Author
John Grisham  3.781538  3.52  3.98

In [183]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Which was their highest-rated book?
john_grisham_books.loc [
    john_grisham_books.groupby('Author')['Book_average_rating'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold
561,John Grisham,2013.0,Sycamore Row,3.98,fiction,7.31,3969

In [184]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Which was their lowest-rated book?
john_grisham_books.loc [
    john_grisham_books.groupby('Author')['Book_average_rating'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold
1065,John Grisham,2014.0,Gray Mountain,3.52,nonfiction,0.99,106

In [185]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#What is their average sale price?
john_grisham_books.groupby('Author')['sale price'].agg(['mean', 'min', 'max'])

                  mean   min   max
Author
John Grisham  4.291538  0.99  8.59

In [186]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Which was their most expensive book?
john_grisham_books.loc [
    john_grisham_books.groupby('Author')['sale price'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold
857,John Grisham,2004.0,The Last Juror,3.85,nonfiction,8.59,2862

In [187]:
#Focus on the top 3 authors who have published the most books
#Top 2: John Grisham
#Which was their least expensive book?
john_grisham_books.loc [
    john_grisham_books.groupby('Author')['sale price'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold
302,John Grisham,1994.0,The Chamber,3.76,fiction,0.99,295

In [188]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
nicholas_sparks_books = books_v5[books_v5['Author'] == 'Nicholas Sparks']
nicholas_sparks_books

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
21,21,2000.0,The Rescue,Nicholas Sparks,english,Intermediate,4.10,142092,fiction,0.000,2.99,"Amazon Digital Services, Inc.",2866,8569.34
40,40,2003.0,The Guardian,Nicholas Sparks,english,Intermediate,4.14,136427,fiction,0.000,0.99,"Amazon Digital Services, Inc.",1892,1873.08
91,91,2002.0,Nights in Rodanthe,Nicholas Sparks,english,Intermediate,3.82,129807,fiction,3362.262,4.99,"Amazon Digital Services, Inc.",1123,5603.77
152,152,2001.0,A Bend in the Road,Nicholas Sparks,english,Intermediate,4.02,116800,fiction,811.920,1.99,HarperCollins Publishers,680,1353.20
155,155,2003.0,The Wedding,Nicholas Sparks,english,Intermediate,3.98,118045,fiction,395.010,0.99,"Amazon Digital Services, Inc.",665,658.35
185,185,2007.0,The Choice,Nicholas Sparks,english,Intermediate,3.99,93479,fiction,0.000,2.99,"Amazon Digital Services, Inc.",496,1483.04
290,290,2010.0,The Best of Me,Nicholas Sparks,english,Intermediate,3.91,103915,fiction,184.734,0.99,"Amazon Digital Services, Inc.",311,307.89
567,567,2012.0,The Longest Ride,Nicholas Sparks,english,Excellent,4.14,71276,fiction,0.000,0.99,"Amazon Digital Services, Inc.",3942,3902.58
883,883,2003.0,True Believer,Nicholas Sparks,english,Intermediate,3.80,62840,fiction,0.000,4.99,"Amazon Digital Services, Inc.",4440,22155.60
928,928,2004.0,At First Sight,Nicholas Sparks,english,Intermediate,3.81,62219,fiction,65.340,0.99,"Amazon Digital Services, Inc.",4320,4276.80

In [189]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
nicholas_sparks_books['Author_Rating'].value_counts()

Author_Rating
Intermediate    9
Excellent       1
Name: count, dtype: int64

In [190]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Publication window
nicholas_sparks_books.groupby('Author')['Publishing Year'].agg(['min', 'max'])

                    min     max
Author
Nicholas Sparks  2000.0  2012.0

In [191]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Publication window & number of yearly publications
nicholas_sparks_books['Publishing Year'].sort_values(ascending = False).value_counts().head(10)

Publishing Year
2003.0    3
2012.0    1
2007.0    1
2010.0    1
2004.0    1
2002.0    1
2001.0    1
2000.0    1
Name: count, dtype: int64

In [192]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#What is the most written genre for this author?
nicholas_sparks_books['genre'].value_counts()

genre
fiction    10
Name: count, dtype: int64

In [193]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Which books did they sell the most?
nicholas_sparks_books['units sold'].sort_values(ascending = False).head(3)

883    4440
928    4320
567    3942
Name: units sold, dtype: int64

In [194]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Which books did they sell the most?
nicholas_sparks_books.loc[[883, 928, 567]]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
883,883,2003.0,True Believer,Nicholas Sparks,english,Intermediate,3.80,62840,fiction,0.00,4.99,"Amazon Digital Services, Inc.",4440,22155.60
928,928,2004.0,At First Sight,Nicholas Sparks,english,Intermediate,3.81,62219,fiction,65.34,0.99,"Amazon Digital Services, Inc.",4320,4276.80
567,567,2012.0,The Longest Ride,Nicholas Sparks,english,Excellent,4.14,71276,fiction,0.00,0.99,"Amazon Digital Services, Inc.",3942,3902.58

In [195]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#How many books did they sell on average?
nicholas_sparks_books['units sold'].mean()

np.float64(2073.5)

In [196]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#What is the average rating for this author?
nicholas_sparks_books.groupby('Author')['Book_average_rating'].agg(['mean', 'min', 'max'])

                  mean  min   max
Author
Nicholas Sparks  3.971  3.8  4.14

In [197]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Which was their highest-rated book?
nicholas_sparks_books.loc [
    nicholas_sparks_books.groupby('Author')['Book_average_rating'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
40,Nicholas Sparks,2003.0,The Guardian,4.14,fiction,0.99,1892,1873.08

In [198]:
#Focus on the top 3 authors who have published the most books#Top 3: Nicholas Sparks
#Which was their lowest-rated book?
nicholas_sparks_books.loc [
    nicholas_sparks_books.groupby('Author')['Book_average_rating'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
883,Nicholas Sparks,2003.0,True Believer,3.8,fiction,4.99,4440,22155.6

In [199]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#What is their average sale price?
nicholas_sparks_books.groupby('Author')['sale price'].agg(['mean', 'min', 'max'])

                 mean   min   max
Author
Nicholas Sparks  2.29  0.99  4.99

In [200]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Which was their most expensive book?
nicholas_sparks_books.loc[
    nicholas_sparks_books.groupby('Author')['sale price'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
91,Nicholas Sparks,2002.0,Nights in Rodanthe,3.82,fiction,4.99,1123,5603.77

In [201]:
#Focus on the top 3 authors who have published the most books
#Top 3: Nicholas Sparks
#Which was their most expensive book?
nicholas_sparks_books.loc[
    nicholas_sparks_books.groupby('Author')['sale price'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
40,Nicholas Sparks,2003.0,The Guardian,4.14,fiction,0.99,1892,1873.08

In [202]:
#Which authors have sold the most books?
books_v5.groupby('Author')['units sold'].sum().sort_values(ascending = False).head()

Author
Stephen King                      278322
Janet Evanovich                   181089
Lemony Snicket, Brett Helquist    158973
Jim Butcher                       145827
Robert Jordan                     126168
Name: units sold, dtype: int64

In [203]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Number of published books
janet_evanovich_books = books_v5[books_v5['Author'] == 'Janet Evanovich']
janet_evanovich_books['Author'].value_counts()

Author
Janet Evanovich    9
Name: count, dtype: int64

In [204]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Number of published books
janet_evanovich_books

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
381,381,1996.0,Two for the Dough,Janet Evanovich,english,Excellent,4.11,116171,nonfiction,1306.692,9.99,"Amazon Digital Services, Inc.",5886,58801.14
465,465,1997.0,Three to Get Deadly,Janet Evanovich,english,Excellent,4.14,113400,fiction,665.874,6.49,Hachette Book Group,4617,29964.33
536,536,1998.0,Four to Score,Janet Evanovich,english,Excellent,4.17,106871,fiction,90.882,0.99,"Amazon Digital Services, Inc.",4131,4089.69
620,620,2000.0,Hot Six,Janet Evanovich,english,Excellent,4.18,99329,fiction,0.000,3.99,"Amazon Digital Services, Inc.",48600,193914.00
650,650,1999.0,High Five,Janet Evanovich,english,Excellent,4.17,92737,children,402.930,5.55,"Amazon Digital Services, Inc.",43200,239760.00
695,695,2001.0,Seven Up,Janet Evanovich,english,Excellent,4.15,94506,fiction,792.252,11.19,HarperCollins Publishers,36072,403645.68
736,736,2003.0,To the Nines,Janet Evanovich,english,Excellent,4.16,86963,fiction,841.698,11.99,Penguin Group (USA) LLC,32832,393655.68
846,846,2002.0,Janet Evanovich Three and Four Two-Book Set (S...,Janet Evanovich,english,Excellent,4.34,63691,fiction,101.700,1.50,HarperCollins Publishers,2889,4333.50
859,859,2005.0,Eleven on Top,Janet Evanovich,english,Excellent,4.15,84363,fiction,507.822,7.49,Penguin Group (USA) LLC,2862,21436.38

In [205]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Publication window
janet_evanovich_books.groupby('Author')['Publishing Year'].agg(['min', 'max'])

                    min     max
Author
Janet Evanovich  1996.0  2005.0

In [206]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Publication window & number of yearly published books
janet_evanovich_books['Publishing Year'].sort_values(ascending = False).value_counts().head(10)

Publishing Year
2005.0    1
2003.0    1
2002.0    1
2001.0    1
2000.0    1
1999.0    1
1998.0    1
1997.0    1
1996.0    1
Name: count, dtype: int64

In [207]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#
janet_evanovich_books['Author_Rating'].value_counts()

Author_Rating
Excellent    9
Name: count, dtype: int64

In [208]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#
janet_evanovich_books['genre'].value_counts()

genre
fiction       7
nonfiction    1
children      1
Name: count, dtype: int64

In [209]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#
janet_evanovich_books['units sold'].sort_values(ascending = False).head(3)

620    48600
650    43200
695    36072
Name: units sold, dtype: int64

In [210]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#
janet_evanovich_books.loc[[620,650,695]]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
620,620,2000.0,Hot Six,Janet Evanovich,english,Excellent,4.18,99329,fiction,0.000,3.99,"Amazon Digital Services, Inc.",48600,193914.00
650,650,1999.0,High Five,Janet Evanovich,english,Excellent,4.17,92737,children,402.930,5.55,"Amazon Digital Services, Inc.",43200,239760.00
695,695,2001.0,Seven Up,Janet Evanovich,english,Excellent,4.15,94506,fiction,792.252,11.19,HarperCollins Publishers,36072,403645.68

In [211]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#
janet_evanovich_books['units sold'].mean()

np.float64(20121.0)

In [212]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#
janet_evanovich_books.groupby('Author')['Book_average_rating'].agg(['mean', 'min', 'max'])

                     mean   min   max
Author
Janet Evanovich  4.174444  4.11  4.34

In [213]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Which was their highest-rated book?
janet_evanovich_books.loc [
    janet_evanovich_books.groupby('Author')['Book_average_rating'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
846,Janet Evanovich,2002.0,Janet Evanovich Three and Four Two-Book Set (S...,4.34,fiction,1.5,2889,4333.5

In [214]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Which was their lowest-rated book?
janet_evanovich_books.loc [
    janet_evanovich_books.groupby('Author')['Book_average_rating'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
381,Janet Evanovich,1996.0,Two for the Dough,4.11,nonfiction,9.99,5886,58801.14

In [215]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#What is their average sale price?
janet_evanovich_books.groupby('Author')['sale price'].agg(['mean', 'min', 'max'])

                     mean   min    max
Author
Janet Evanovich  6.575556  0.99  11.99

In [216]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Which was their most expensive book?
janet_evanovich_books.loc[
    janet_evanovich_books.groupby('Author')['sale price'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
736,Janet Evanovich,2003.0,To the Nines,4.16,fiction,11.99,32832,393655.68

In [217]:
#Focus on the top 3 best-selling authors
#Top 2: Janet Evanovich
#Which was their least expensive book?
janet_evanovich_books.loc[
    janet_evanovich_books.groupby('Author')['sale price'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
536,Janet Evanovich,1998.0,Four to Score,4.17,fiction,0.99,4131,4089.69

In [218]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
snicket_helquist_books = books_v5[books_v5['Author'] == 'Lemony Snicket, Brett Helquist']
snicket_helquist_books['Author'].value_counts()

Author
Lemony Snicket, Brett Helquist    8
Name: count, dtype: int64

In [219]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
snicket_helquist_books

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
342,342,1999.0,The Reptile Room,"Lemony Snicket, Brett Helquist",english,Intermediate,3.95,130213,fiction,721.554,4.99,Simon and Schuster Digital Sales Inc,241,1202.59
502,502,2000.0,The Wide Window,"Lemony Snicket, Brett Helquist",english,Intermediate,3.91,118624,fiction,96.822,0.99,"Amazon Digital Services, Inc.",4401,4356.99
632,632,2000.0,The Miserable Mill,"Lemony Snicket, Brett Helquist",english,Intermediate,3.83,101325,fiction,837.438,10.99,Penguin Group (USA) LLC,46872,515123.28
694,694,2000.0,The Austere Academy,"Lemony Snicket, Brett Helquist",english,Intermediate,3.97,99311,fiction,0.000,0.99,"Amazon Digital Services, Inc.",36288,35925.12
702,702,2001.0,The Vile Village,"Lemony Snicket, Brett Helquist",english,Intermediate,3.94,89733,fiction,424.092,5.99,Penguin Group (USA) LLC,35640,213483.60
758,758,2001.0,The Ersatz Elevator,"Lemony Snicket, Brett Helquist",english,Excellent,4.01,90071,nonfiction,138.504,1.99,Random House LLC,31104,61896.96
945,945,2003.0,The Slippery Slope,"Lemony Snicket, Brett Helquist",english,Intermediate,4.00,81362,fiction,593.340,8.99,Penguin Group (USA) LLC,4320,38836.80
1018,1018,2002.0,The Carnivorous Carnival,"Lemony Snicket, Brett Helquist",english,Intermediate,3.97,83981,fiction,0.000,0.99,"Amazon Digital Services, Inc.",107,105.93

In [220]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
snicket_helquist_books['Author_Rating'].value_counts()

Author_Rating
Intermediate    7
Excellent       1
Name: count, dtype: int64

In [221]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Publication window
snicket_helquist_books.groupby('Author')['Publishing Year'].agg(['min', 'max'])

                                   min     max
Author
Lemony Snicket, Brett Helquist  1999.0  2003.0

In [222]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Publication window & number of yearly publications
snicket_helquist_books['Publishing Year'].sort_values(ascending = False).value_counts().head(10)

Publishing Year
2000.0    3
2001.0    2
2003.0    1
2002.0    1
1999.0    1
Name: count, dtype: int64

In [223]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#What is the most written genre for these co-authors?
snicket_helquist_books['genre'].value_counts()

genre
fiction       7
nonfiction    1
Name: count, dtype: int64

In [224]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Which books did they sell the most?
snicket_helquist_books['units sold'].sort_values(ascending = False).head(3)

632    46872
694    36288
702    35640
Name: units sold, dtype: int64

In [225]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Which books did they sell the most?
snicket_helquist_books.loc[[632,694,702]]

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,publisher revenue,sale price,Publisher,units sold,Gross sales
632,632,2000.0,The Miserable Mill,"Lemony Snicket, Brett Helquist",english,Intermediate,3.83,101325,fiction,837.438,10.99,Penguin Group (USA) LLC,46872,515123.28
694,694,2000.0,The Austere Academy,"Lemony Snicket, Brett Helquist",english,Intermediate,3.97,99311,fiction,0.000,0.99,"Amazon Digital Services, Inc.",36288,35925.12
702,702,2001.0,The Vile Village,"Lemony Snicket, Brett Helquist",english,Intermediate,3.94,89733,fiction,424.092,5.99,Penguin Group (USA) LLC,35640,213483.60

In [226]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#How many books did they sell on average?
snicket_helquist_books['units sold'].mean()

np.float64(19871.625)

In [227]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#What is the average rating for these co-authors?
snicket_helquist_books.groupby('Author')['Book_average_rating'].agg(['mean', 'min', 'max'])

                                  mean   min   max
Author
Lemony Snicket, Brett Helquist  3.9475  3.83  4.01

In [228]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Which was their highest-rated book?
snicket_helquist_books.loc [
    snicket_helquist_books.groupby('Author')['Book_average_rating'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
758,"Lemony Snicket, Brett Helquist",2001.0,The Ersatz Elevator,4.01,nonfiction,1.99,31104,61896.96

In [229]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Which was their lowest-rated book?
snicket_helquist_books.loc [
    snicket_helquist_books.groupby('Author')['Book_average_rating'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
632,"Lemony Snicket, Brett Helquist",2000.0,The Miserable Mill,3.83,fiction,10.99,46872,515123.28

In [230]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#What is their average sale price?
snicket_helquist_books.groupby('Author')['sale price'].agg(['mean', 'min', 'max'])

                                mean   min    max
Author
Lemony Snicket, Brett Helquist  4.49  0.99  10.99

In [231]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Which was their most expensive book?
snicket_helquist_books.loc[
    snicket_helquist_books.groupby('Author')['sale price'].idxmax(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
632,"Lemony Snicket, Brett Helquist",2000.0,The Miserable Mill,3.83,fiction,10.99,46872,515123.28

In [232]:
#Focus on the top 3 best-selling authors
#Top 3: Lemony Snicket & Brett Helquist
#Which was their least expensive book?
snicket_helquist_books.loc[
    snicket_helquist_books.groupby('Author')['sale price'].idxmin(),
    ['Author', 'Publishing Year', 'Book Name', 'Book_average_rating', 'genre', 'sale price', 'units sold', 'Gross sales']
]

,Author,Publishing Year,Book Name,Book_average_rating,genre,sale price,units sold,Gross sales
502,"Lemony Snicket, Brett Helquist",2000.0,The Wide Window,3.91,fiction,0.99,4401,4356.99